### ISSUE TITLE
documentation for ks to tk migration

### ISSUE THREAD

**Issue by abh** [grafana/tanka#118]
@sh0rez wrote in #108 

> Just out of interest, what would have had to be done to migrate to Tanka? We designed tk to be very similar to ks so that it should be a flawless experience for most users .. could you elaborate a bit so we could improve? :D

The learning curve for ksonnet was pretty steep, so to be honest I just figured out enough to get the applications going that I needed it for and then I edited away without putting much effort into understanding how things worked underneath. 

I think I'm mostly getting stuck because I don't understand what the "magic" that ksonnet did and how to replace it. For example with `ks` the params.libsonnet files in environments/{beta, prod} and components/ were automatically loaded and merged. Or rather, the environment specific one was loaded and then finished with

```
{
  components: {
    [x]: envParams.components[x] + globals
    for x in std.objectFields(envParams.components)
  },
}
```

to do the merging. However, in my components I could just ask for `local params = std.extVar('__ksonnet/params').components.foobar;` and get the `foobar` parameters.  I'm not sure how to make this work with tanka.

With ksonnet all the specified components were automatically, I think, imported and merged together.  It's probably a straightforward bit of jsonnet to add to my `main.libsonnet`, but it's not obvious to me how.

**Comment by malcolmholmes** [comment]
The whole params setup is one of the things that Tanka discards from the Ksonnet world. It just makes things unduly complicated.

The fact is, we have a JSON tree that can have objects that won't be rendered into the final output (using `::` ). Therefore, we might as well use that for our configuration, rather than overlaying a whole new (unnecessary) concept and system.

So, for example, have a config object in the root of your libs (as `lib/app/app.libsonnet`):

```
{
  config+:: {
    service_port: 80,
  }
}
```

Then, if you wish to override this in your environment, you simply have (in `environments/dev/main.jsonnet`):

```
local app = import "app/app.libsonnet";
app + {
 config+:: {
   service_port: 8080,
  }
}
```

That way, you have the ability to override configs, and all the benefits of jsonnet available to you too.

**Comment by abh** [comment]
I still don't get it. I think because I don't understand how jsonnet works. :-)

I tried making an example -- I define some configuration here (`config` goes into a secret and `params` is where I'll define application parameters):

https://github.com/abh/tanka-test/blob/master/lib/config.libsonnet

I build the "app" (which right now is just the secret) here:
https://github.com/abh/tanka-test/blob/master/lib/ntppool/app.libsonnet

from this environment, where i override one of the 'config' values.

https://github.com/abh/tanka-test/blob/master/environments/dev/main.jsonnet

However, running this with `jsonnet` or `tk`, the overrides from the environment doesn't take effect, I still get the value from lib/config.libsonnet.

**Comment by sh0rez** [comment]
Hi, I have forked your example and updated it to the ways Grafana uses Jsonnet and Tanka: https://github.com/sh0rez/tanka-example. 

We basically have libraries (under `lib/`) that consist of `_config/$APPNAME` defaults and a `main.jsonnet` file per environment that is chaining all these libs together into one big object. Optionally, the defaults of the libraries an be overwritten here if required.

We also have `ksonnet-util/kausal.libsonnet` which is our enhanced version of `k.libsonnet` that is easier to use.

Please also note the `lib/k.libsonnet` file, which does nothing but import the actual `k.libsonnet` this project should use. This is required, because a `k.libsonnet` is generated for a specific cluster version and incompatible with others. For example, `ksonnet.beta.3` is not compatible with 1.16 and above.  
To resolve this, we use a unversioned import `k.libsonnet` that resolves to the correct version in the mentioned file.

Does this help you? If you have any questions, just let me know here or in the #tanka channel on the Grafana Slack: https://grafana.slack.com
