### ISSUE TITLE
looking to integrate with kapp deployment tool

### ISSUE THREAD

**Issue by cppforlife** [grafana/tanka#151]
hey all,

thanks for project first of all, i'm eager to see where yall are headed.

i'm one of the authors of kapp (https://github.com/k14s/kapp; https://get-kapp.io). kapp is a deployment tool that accepts plain yaml/json k8s configuration and drives a deployment by first performing diff, then based on diff results creating, deleting, updating resources.

from what i understand tanka includes both config generation (jsonnet facilities) and deployment tool (that drives kubectl). im curious about your choice on rolling both of these concerns into a single tool vs having two separate standalone tools that are loosely coupled (by that i mean depending on unixy mechanism to transfer content e.g. `kapp deploy -a foo -f <(tk show)`).

**Comment by sh0rez** [comment]
So, the design idea for Tanka is to provide a tool that takes JSON compatible languages (though we only focus on Jsonnet for now) and provide a nice developer experience (`show`, `diff`, `apply` workflow, confidence in working, good error messages, command line completion, `tk status` - an overview and many more).

Tanka tries to become a full solution for configuration Kubernetes – in a single command. Much like the `go` command got you covered when it comes to working with go. While this is not strictly the UNIX philosophy (you could have a compiler, a linker, a lint and vet tool, a doc tool, etc), it has proven to be incredibly easy for users to use. because they have one command that gets them covered.

I see `kapp` is having a similar approach, though being focused on only providing a developer experience, which is still a very cool thing. Due to the overlapping functionality, what would it bring both projects to integrate?

**Comment by cppforlife** [comment]
thanks for circling back quickly.

> Tanka tries to become a full solution for configuration Kubernetes – in a single command. Much like the go command got you covered when it comes to working with go. 

one of the reasons ive ended building multiple smaller tools that interoperate well together was because i noticed that many users customize their workflow heavily. for configuration some use jsonnet, others, ytt, etc. same goes for secret management. hence i think by making tools single-purpose and well polished it's less of a barrier to integrate (especially within existing workflows). that's just my take on that though.

> it has proven to be incredibly easy for users to use. because they have one command that gets them covered.

i do agree that basic workflow is easier for users when it's all "bundled in". as they progress in my experience more knobs are necessary for integration.

>  Due to the overlapping functionality, what would it bring both projects to integrate?

im not certain. i'm interested in swapping few ideas in deployment or configuration areas. (not sure if yall have a community call to join).

one possibility i see from my side is within kapp-controller project (example CRD: https://github.com/k14s/kapp-controller/blob/master/examples/simple-app-git/1.yml). i was planning to implement jsonnet template step (in addition to existing ytt step). tanka show command may be of help here as it provides nice jsonnet experience.

from tanka side, i believe `tk show | kapp deploy -a app1 -f- --yes` should already work. if tk is embracing single tool workflow, is there a possibility of making deployment part "pluggable" so that kapp deploy can be executed by tk?

**Comment by sh0rez** [comment]
#### Integrating
So, Tanka is basically "Batteries included but swappable". Low level operations (such as `show` or even `eval`) are available for use in other tools. As you have pointed out, this could be easily piped to `kapp`. 

This also gives users all the flexibility they might need, they can hand wire all tools they need. Do you think it would still be necessary if Tanka was calling `kapp` instead? I have the feeling that this overcomplicates it, because we need to come up with a new way of configuring it, etc. Bash pipes are powerful and should probably just be used here.

#### Community call
Well, until yesterday the project was not announced and did not quite have a community outside of Grafana Labs, thus no call yet. 

For sure we can set one up once in a while. Until then, the less formal way of communication is Slack: https://grafana.slack.com, join the `#tanka` channel.

**Comment by davidovich** [comment]
#214 (exporting) can be used as a manifest generator for input to kapp.
