### ISSUE TITLE
How does Tanka compare to Bazel+rules_{docker,jsonnet,k8s}?

### ISSUE THREAD

**Issue by EdSchouten** [grafana/tanka#153]
The [Bazel build system](https://bazel.build/) has support for writing custom build rules in a language called Starlark. One of the rulesets is called [rules_k8s](https://github.com/bazelbuild/rules_k8s), which allows you to do push Kubernetes objects. Because rules_k8s integrates with [rules_docker](https://github.com/bazelbuild/rules_docker), you can even let your Kubernetes deployments depend on build targets that yield container images, which causes them to be pushed into your container registry when deploying.

Rules_k8s does not use any forms of templating, but there is also no need to. Because Bazel is a build system, you can use [rules_jsonnet](https://github.com/bazelbuild/rules_jsonnet) to generate the manifests that are pushed by rules_k8s.

This raises the question: how does Tanka relate to the above? Could it be thought of as a subset of the above (i.e., just the application of Kubernetes objects, but not the container image pushing)?

**Comment by tomwilkie** [comment]
Bazel is a build system, tanka is a config management system.  The questions if like asking "whats the difference between `make` and `ansible`."

Bazel is designed for fast and correct building of artifacts through declared dependancies, isolated build steps, hashing and caching.  Tanka is about making config (for k8s) shareable, extensible and management at scale.  Tanka allows you to build abstractions, manage rollouts etc.

You could potentially use them together, and I agree Bazel is branching out into some of the deployment steps for k8s, but really they are pretty separate things.

**Comment by EdSchouten** [comment]
> Bazel is a build system, tanka is a config management system. The questions if like asking "whats the difference between `make` and `ansible`."

I think it’s important to keep in mind that those are just labels we attach to pieces of software. It doesn’t mean comparisons between them are any less valid. For example, just because Jsonnet is a ‘templating language’ doesn’t mean it’s incomparable to, say, Haskell. At the end of the day it’s all about the functionality they offer, right?

You make a valid point about Tanka managing rollouts. Bazel’s rules_k8s only performs rollouts interactively, but does in no way statefully track them in the background/manage them. I can imagine people may find this useful.

> Tanka is about making config (for k8s) shareable, extensible and management at scale.

Bazel [also provides facilities](https://docs.bazel.build/versions/master/external.html) to make source code shareable, extensible and manageable at scale. If you treat [infrastructure as code](https://en.wikipedia.org/wiki/Infrastructure_as_code), Bazel and Tanka would thus be equivalent in that regard.

Would it make sense to publish some kind of article/documentation page that describes the relationship between tools like Tanka, Bazel, Ksonnet, etc. in more detail? Examples: [Clang](https://clang.llvm.org/comparison.html), [Jsonnet](https://jsonnet.org/articles/comparisons.html).

**Comment by sh0rez** [comment]
> I think it’s important to keep in mind that those are just labels we attach to pieces of software

Can't fully agree. I would argue software is meant for the purpose it is developed for. 

Bazel was designed, developed and meant for very sophisticated building of source code, much like @tomwilkie outlined above, and it performs especially well at this.  
While you might be able to use it for other means because it is flexible enough, it still was never specifically optimized for that approach.  
This becomes already obvious in your description: It is possible, but you need to plug all these pieces together by hand, which makes it appear a bad fit.

Tanka (and Helm, ksonnet, kustomize, etc) were designed with another issue in mind: *Configuring Kubernetes*. These tools are very specific and highly optimized for this single problem and are probably more user friendly at this.

To stick to Tom's example:

You could setup your entire cloud stack with `make`. The is `gcloud`, `aws` and so on available, allowing you to achieve your goal, if you put enough effort in it.  
I guess we can agree that this would be a waste time, because there are better tools like `ansible` or `terraform` available that allow you to complish the task faster, because they are more specialized and thus perform better at this single task.

**Comment by EdSchouten** [comment]
> but you need to plug all these pieces together by hand, which makes it appear a bad fit.

This is just a matter of where you draw the boundaries, right? If someone would use Tanka to deploy a couple of in-house developed microservices written in Go and Java, the pieces they would plug together would be Tanka, Maven, 'go build', 'docker build', 'docker push', etc. Does that mean that those tools are a bad fit as well?

**Comment by sh0rez** [comment]
I feel like we lose the focus on the topic a bit here.

To answer your question:
> This raises the question: how does Tanka relate to the above? Could it be thought of as a subset of the above (i.e., just the application of Kubernetes objects, but not the container image pushing)?

Tanka is a tool for the specific use-case of managing resources that define the desired state of Kubernetes. Bazel on the other hand builds software. Bazel might be able to do the same as Tanka, but it will take more time and effort. IMHO this is not worth it, if better tools are around (Tanka, helm, ksonnet, etc). 

Regarding comparison: I still don't think these are on a level where a comparison would make a lot of sense. In case somebody else wonders as well, we now have this issue people can read.

**Comment by EdSchouten** [comment]
Perfect! Thanks for taking your time to answer.

**Comment by sh0rez** [comment]
You are welcome :smiley:
