### ISSUE TITLE
nativeFunc plugins

### ISSUE THREAD

**Issue by xunleii** [grafana/tanka#171]
Hi all,
First of all, thanks for this project.

I'd love to be able to extend Tanka to use native custom jsonnet methods. I have several use cases requiring it. For example, I would like to automatically resolve IP addresses from domains directly via Jsonnet, instead of using external variables.

Do you think is it possible to add this feature to Tanka ?

I made a draft based on the Go plugins. It is easy to use but requires rebuilding the plugin for each version of Tanka (this can be annoying but, in my opinion, it can be easily overcome through CI pipelines). You can found this draft at https://github.com/xunleii/tanka/tree/feat-add-tanka-plugin .

**Comment by cyriltovena** [comment]
Plugins for tanka, that sounds like a reasonable and interesting feature.

However we shouldn’t need to rebuild tanka, and we should be able to install them on the fly.

We might want to take inspiration from terraform plugins experience.

**Comment by pstibrany** [comment]
Problem with native jsonnet methods is that they break jsonnet contract: to be a side-effect free language for data templating.

Even your example, resolving IP addresses, is dependant on so many things that change (time, network configuration, computer where it runs), that it may not be a good fit to the language. I would prefer if two people deploying stuff via Tanka always deployed the same configuration.

**Comment by xunleii** [comment]
@cyriltovena with Go plugin, we only need to rebuild the plugin when the Tanka code changes (each release). And, in my opinion, the terraform plugin way is a bit too overkill for this kind of feature (it manages multi processes, one per plugin, and communicate with them through gRPC).

@pstibrany I agree with you, for this use case (and many of my others uses cases). But external plugins can also be used to implement secret provider (like Vault or GPG encryption), to download object stored in object storage and many other use cases that *doesn't have huge* side-effects.

**Comment by sbarzowski** [comment]
> For example, I would like to automatically resolve IP addresses from domains directly via Jsonnet, instead of using external variables.

> Even your example, resolving IP addresses, is dependant on so many things that change (time, network configuration, computer where it runs), that it may not be a good fit to the language. I would prefer if two people deploying stuff via Tanka always deployed the same configuration.

> I agree with you, for this use case (and many of my others uses cases). But external plugins can also be used to implement secret provider (like Vault or GPG encryption), to download object stored in object storage and many other use cases that doesn't have huge side-effects.

In all of these cases the output is dependent directly on an external service, and that's a bad thing in itself. Ideally the config would depend exclusively on the stuff you keep in your repo. That's the setup which is the most predictable, robust and easy to debug.

However, sometimes a pragmatic compromise is necessary. In particular, secret management is a pretty compelling case for getting data from an external service. There are some ideas to make it easier to use external data sources, while preserving as much as possible of the "pure and predictable" feel. This is discussed in #168 (for Tanka) and https://github.com/google/go-jsonnet/issues/338 as a general upstream solution. It's still about choosing the lesser evil, though.

> Problem with native jsonnet methods is that they break jsonnet contract: to be a side-effect free language for data templating.

Native functions were intended for implementation of pure functions which were not practical to implement in Jsonnet, because that would be too slow (e.g. hash functions) and cases when the logic is just too complex to reimplement (e.g. yaml parsing, btw we plan to support this upstream). They were **not** intended for IO.

**Comment by sbarzowski** [comment]
BTW I don't know your use case, but resolving DNS at the time of generating your config sounds a bit suspicious to me.

1) 3rd party services should probably be referred to using domain names in the final config - this way you won't need to redeploy when the IP changes.
2) The same applies to your services, where the DNS is the source of truth and you don't control the IP.
3) If the IP is stable and you control it, then you may not want to depend on the DNS servers at all to provide it for you - you can keep the mapping in the repo instead (and maybe even populate the DNS from it).

Ofc I don't know your setup, so this thinking be completely wrong in your case...

**Comment by sh0rez** [comment]
I agree with what @sbarzowski said.

#### More issues
Furthermore, regardless of whether native functions are used for IO or data processing, I do not think they are a good fit for plugins. Being decoupled from Tanka itself, allowing plugins might and will most probably lead to a bloat of Jsonnet native functions, probably undocumented. Even worse, it will lead to Jsonnet code, that depends not only on Tanka, but also some possibly unknown plugin, which harms one of Tanka's core design choices, **shareability**.

Imagine having a library (let's call it `kubernetes-monitor`) and it fails because the nativeFunc `convertKube` is missing. Why? What plugin is supposed to provide it? What does it even do? Jsonnet is not able to deliver the promise of a self contained config anymore.

#### Possible solution
Nevertheless, I we must acknowledge the issue of more sophisticated environments, that require information from the outside.

Jsonnet already has `extVars`, values (can be entire objects, etc) that are injected before evaluation.
And because they are injected from the outside, it is clear to everyone that this data needs to be taken care of by other means.

I guess you could resolve your DNS data beforehand and pass it in ... this is the way such data is supposed to be handled.

**Comment by xunleii** [comment]
Thank you all for your responses :)
When I had this idea (resolve DNS through Jsonnet), I wanted to use only one tool to generate all of my Kube stuff.

But thanks to your answers, I better understand what Tanka is and, with extVars and some 3rd party tools, I could achieve what I want.
