### ISSUE TITLE
tk completion breaks for partial flags

### ISSUE THREAD

**Issue by davidovich** [grafana/tanka#191]
tk fails partial completion of flags. If I type `tk show --<tab>` the completion suggestion works, but if I want to complete `tk show --da<tab>` (wanting to complete `--dangerous-allow-redirect`) I get an error. 

Consider this session:

```bash
# tk show --<tab>
--dangerous-allow-redirect  --extCode                   --extVar                    --target                    --verbose                   
# tk show --da<tab>Error: unknown flag: --da

... removed tk help output ...

Ouch: unknown flag: --da
```

**Comment by sh0rez** [comment]
Hey, thanks for reporting.

This is odd, because the exact thing works for me.

Could you please provide some more details on your Environment? Which shell is used, any shell frameworks, contents of bashrc/zshrc?

**Comment by davidovich** [comment]
Reproduced on MacOS Mojave 10.14.6 (with a manual brew based bash update):

```bash
david$ bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

and in a dockerized dev env based on ubuntu:latest (18.04 LTS) with default bash:

```bash
# bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

**Comment by davidovich** [comment]
strange, but `which -a tk` yields two entries (on my mac):
```bash
david$ which -a tk
/Users/david/go/bin/tk
/Users/david/go/bin/tk
```

**Comment by davidovich** [comment]
last line of my ~/.bashrc:

`complete -C /usr/local/bin/tk tk`

**Comment by sh0rez** [comment]
Okay, I can reproduce. This seems to happen:

- only with `bash` (`zsh` works fine)
- across platforms (osx and ubuntu tested)

I suspect the issue to be with the `posener/complete` library, which handles  completion for us. Just seen that `v2` of  that is available, maybe we should switch? Will investigate if I find time during FOSDEM, otherwise afterwards. Thanks for reporting @davidovich!

**Comment by davidovich** [comment]
Is there a reason tk doesn't use cobra completions ?  Delegating the whole command structure to another library seems heavy handed. `posener/complete` seems to not be very good at out of order arguments (failing to complete if flags are not in the right order). <- this though might be related to the current bug.

I find it a bit odd that tanka changes files under my feet. For example, I use ~/.profile for configuring completions (because there is no need to do that in ~/.bashrc, which is loaded even on non-interactive mode). So for me, completions do not work unless I source ~/.bashrc after installing (but I guess this is true (needing to source) for everyone).

**Comment by sh0rez** [comment]
We considered cobra completions, but they basically failed us. They only work really well on bash as it seems, the API was complicated and after all, just a very overengineered way of providing a standard bash script ... which would need to be written for zsh again, and for fish again, etc.

I was not able to get zsh to work in 2 hours, so I abandoned cobra altogether.

posener/complete was cool because it allows us to provide suggestions directly from Go ... using Go code. We could use all of our fancy logic to compute these ... like fetching valid environments, loading kubectl contexts, etc.

Having to duplicate the command structure ... well yes, not super clean but completely handled inside of a single package, so it seemed fine.
