### ISSUE TITLE
Integration with Popular Rollout Tooling

### ISSUE THREAD

**Issue by joshatcaper** [grafana/tanka#193]
Recently my company was evaluating what config tool we should use. We eventually settled on Helm because it integrated with other popular tools. Does tanka plan on building out integrations with other popular tools? I don't have an exhaustive list of tools but if others comment I can add into this list.

Some tools that I think would integrate well into the tanka workflow:

1. [Skaffold](https://skaffold.dev/): https://github.com/GoogleContainerTools/skaffold/issues/3498
2. [Tilt](https://github.com/windmilleng/tilt): No open issue right now 

Are integrating or replacing these tools part of the goals of this project? Is there any roadmap that can be attached to this?

**Comment by sh0rez** [comment]
Hey @joshatcaper, thanks for raising this issue!

We have not yet considered integrating Tanka with the broader ecosystem of CD and similar solutions, because there was no internal requirement and no external demand yet.

Of course it makes perfect sense to do so. I have added a comment to the skaffold issue.

Other tools I can think of:

- https://fluxcd.io/
- https://github.com/tektoncd/pipeline
- https://argoproj.github.io/argo-cd/

**Comment by joshatcaper** [comment]
@sh0rez, thanks for getting back to me. Are you able to share what Grafana does for this use case? What does your local, and CI, build and deploy pipeline look like?

**Comment by sh0rez** [comment]
This is certainly not stale, we will consider it as a point on our roadmap, once we publish that.

**Comment by sh0rez** [comment]
Closing this issue, as there is not much we can do at this point.

Using `tk export` provides a path for most rollout tools to work with. We internally use FluxCD and it works.
