### ISSUE TITLE
Override vendor per environment

### ISSUE THREAD

**Issue by olegmayko** [grafana/tanka#197]
Hi, 
We are using jsonnet for generating  k8s objects and I like the idea introduced by tanka. However, I wonder how to specify different version of vendor dependency per environment described in jsonnetfile. 
For example, prod cluster runs on version x and dev/stage - on x+1 and there are breaking changes between x and x+1, e.g. metrics names; and I need to use release-0.1 of Kube-prometheus for prod and release 0.2 - for dev/stage. Would it be possible?
thanks

**Comment by sh0rez** [comment]
Hi! We do have internally at Grafana Labs exactly the same use-case and are currently working on a solution for this.

In #185 we merged the first part of this feature, adding `<baseDir>/vendor` to the `JPATH`.
> `baseDir` is the directory of your environment, e.g. `environments/default`

So now, when you import e.g. `loki/loki.libsonnet`, Tanka does the following:

1. Look in `<baseDir>/loki/loki.libsonnet`. If it finds nothing:
2. Look in `lib/loki/loki.libsonnet`. If it finds nothing:
3. Look in `<baseDir>/vendor/loki/loki.libsonnet`. If it finds nothing:
4. Look in `vendor/loki/loki.libsonnet`

It considers the most specific (local environments) first, the least specific (project `vendor`) last.

---

To do what you want, you need somehow add your updated library to `<baseDir>/vendor`. For the time being, you can't use `jb` for that, because some features are missing there. We are working on it.

Instead, manually get the new code there, for example using `wget`. Also make sure you use latest Tanka (we released today, https://github.com/grafana/tanka/releases/tag/v0.7.1).

Keep in mind this is a new and experimental feature, but feel free to test it out. Let us know :D

**Comment by sh0rez** [comment]
@olegmayko we have just merged #198, which simplifies this a lot.

To try this out, install latest Tanka `master` (you need `go` for this):

```bash
$ git clone https://github.com/grafana/tanka
$ cd tanka

$ make install
```

Then follow the docs at https://tanka.dev/libraries/overriding#per-environment

**Comment by olegmayko** [comment]
@sh0rez thanks a lot. I have tested it and it works. When do you plan to cut the release?

**Comment by sh0rez** [comment]
We have some fixes we wan't to get in first in the PR's, we'll probably release end of this week / early next week
