### ISSUE TITLE
Prioritize CRD's in diff

### ISSUE THREAD

**Issue by sh0rez** [grafana/tanka#246]
While #244 already does this for apply, the work done in #237 should be extended to `CustomResourceDefinitions` as well.

**Comment by mplzik** [comment]
This will be addressed in a follow-up PR that will cover the rest of #227 . Splitting the original PR made it a bit easier to rewrite and review.

**Comment by mplzik** [comment]
This has been implemented for `apply` in https://github.com/grafana/tanka/pull/244 and https://github.com/grafana/tanka/pull/259; working this out for `diff` is still pending.

**Comment by mplzik** [comment]
A simple experiment (sorting all objects instead of separating the ns/crds/...) showed  that the object order actually doesn't seem to matter for diff -- even with CRDs at the top, `tk diff` on not-yet-installed cert-manager was failing with:
```
$ tk diff .
error: unable to recognize "STDIN": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1alpha2"
exit status 2
```

We might still implement sorting for the UX reasons (having diffs shown in the same order as they willl be applied might help), but there's likely little to no added value besides that.

**Comment by mplzik** [comment]
OTOH, sorting the objects for UX purposes will still require more heavyweight refactoring, since the diff calculation works on two different sets of manifests.

**Comment by zerok** [comment]
I don't think this has a priority right now. Will close and reopen if needed.
