### ISSUE TITLE
Native functions docs don't say how to access the functions

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/tanka#247]
This page: https://tanka.dev/jsonnet/native

Offers juicy functions such as `manifestJSONFromJSON()`, but does not tell us how to access these functions. Are they standalone, using `std.`, using `tanka.`? This omission renders the page effectively useless, unless one already happens to know.

**Comment by jdbaldry** [comment]
I agree the docs could be clearer, but I think it is in part down to the absence of the `std.native` function in the [Jsonnet standard library documentation](https://jsonnet.org/ref/stdlib.html).

To use the documented `parseYAML` native go function, you need to know that it actually called `parseYaml` in the Jsonnet AST. Go and Jsonnet have different style when it comes to naming.

In your Jsonnet code, you need to do something like:
```
{
  my_pod: std.native('parseYaml')(|||
    apiVersion: v1
    kind: Pod
    metadata:
      name: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
  |||),
}
```
The `std.native` function returns the native function identified by the argument (in this case 'parseYaml'). That function is then evaluated with the verbatim string as its argument. 

I imagine the most common use case for this would be something more like having the YAML externally and importing it with `importstr`:
```
{
  my_pod: std.native('parseYaml')(importstr 'pod.yaml'),
}
```

It is worth noting that you now cannot interpret your Jsonnet code without using Tanka as far as I am aware, since the Jsonnet command line tool will not have the native functions available.

I'm more than happy to convert this to more user-friendly technical documentation and submit a PR if it would be useful.

**Comment by jdbaldry** [comment]
@malcolmholmes I just realized that you are almost certainly already aware of how the native functions are used based upon your other contributions to the repo. Sorry about that!

Of course, I'm still happy to put some docs together if you want it?

**Comment by malcolmholmes** [comment]
No worries. Please do make a PR. Also useful could be a little lib that wraps all these so we do have XYZ.parseYAML() etc functions.

**Comment by jdbaldry** [comment]
Yeah I think a library would be a nice addition. It was only when I encountered the `kausal.libsonnet` `manifestYaml` function that I learnt about native functions in Jsonnet.

I'll get something together today. Would you want the lib added as part of this PR?

**Comment by sh0rez** [comment]
No, just do a docs PR please.

Native funcs are really something we inherited from ksonnet and not meant to be a permanent solution, because of the compatibility issues.

Work is already going on to move their functionality into upstream Jsonnet

**Comment by jdbaldry** [comment]
Awesome :) 
Great to hear about them going upstream!
