### ISSUE TITLE
no autocomplete for `<PATH>` on CLI commands

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#352]
I cannot autocomplete paths on commands such as `tk diff <PATH>`

**Comment by malcolmholmes** [comment]
@ghostsquad how are you configuring autocomplete?

**Comment by ghostsquad** [comment]
I'm using ZSH. For reference, the problem appears to be if I've nested my environments, and if I'm running tk from a more top-level directory:

example of the location of the `spec.json`:

```
./deploy/kubernetes/environments/development/spec.json
```

if I try to run `tk diff` from `./` (being the root of my repo) it doesn't try to autocomplete the environments or let me specify the path to the environment.

However, if my PWD is `./deploy/kubernetes/environments` then it does autocomplete `development`

**Comment by Duologic** [comment]
I have been annoyed by that too, if I'm one directory above the Tanka root, then the directory autocomplete just doesn't respond while technically it will just work.

**Comment by sh0rez** [comment]
Let me give some technical background on this.

Tanka implements its own bash completion handler in Go, which allows us to use arbitrarily complex computation to generate those results. ZSH and Fish use Bash compat mode and should just work as well. The `tk completion` command enables the feature for all locally installed shells.

Bespoke directory completion does not actually suggest directories, but instead it uses the code that powers `tk env list` to find environments, starting from the current directory. This code however requires a **`jsonnetfile.json` in the current or enclosing folders**.

When being just one level outside of the this is no longer satisfied and our code returns an empty list, which effectively means no completion.

I see two ways forward here:

1. We could use the last full directory of the already supplied argument to run the search on, instead of `pwd` (in `findBaseDirs`):
https://github.com/grafana/tanka/blob/fdf0ca14f5541c7961efda27037373eee54be874/cmd/tk/args.go#L8-L16

2. We could fallback to the regular directory completion in case environment completion is not possible.

No. 2 is certainly simpler and straightforward to implement.

**Comment by Duologic** [comment]
I'd be all for 2., my general expectation is that I can tab complete from current working dir to wherever the environment exists.

**Comment by ghostsquad** [comment]
You da best!
