### ISSUE TITLE
tk apply slightly confusing output

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#359]
## Description

```
tk apply deploy/environments/production
...
Applying to namespace 'default' of cluster '<REDACTED>' at 'https://<REDACTED>.yl4.us-west-2.eks.amazonaws.com' using context '<REDACTED>'.
```

The reason this is confusing, is that all my manifests have explicitly defined namespace. Additionally, I'm deploying the namespace itself here.

Additionally `spec.json` does not include `namespace` anywhere.

## Expected Output

I'm not entirely sure here. Maybe the output should explicitly list the names and namespaces of the resources it's going to apply **in addition** to outputting the diff. Something like:

```
resources to deploy:
Name			Type		Namespace

App				Deployment	Production	
```

**Comment by sh0rez** [comment]
Tanka manages the default namespace as described at length in https://tanka.dev/namespaces.

Above message could indeed say `Applying to *default* namespace 'foobar' of cluster ...`.
Also when your `spec.json` does not include the `spec.namespace` field, it defaults  to `default`, because we can be sure that namespace at least exists.

You can always verify using `tk status` what namespace tanka recognized for your resources

**Comment by ghostsquad** [comment]
Ya, I've read that page before. So I was hoping this issue could help make it abundantly clear what Tanka is actually going to do.
