### ISSUE TITLE
Now we diff before apply, it seems weird we apply all objects

### ISSUE THREAD

**Issue by tomwilkie** [grafana/tanka#41]
Perhaps we should only apply object we detect a diff in?  WDYT?

**Comment by sh0rez** [comment]
I am uncertain whether this is a good idea.

It feels to me as if there might be side-effects of an apply we cannot detect in diff, so we would miss those.

`kubectl` itself also always applies everything and figures out *server side* what to discard.

This would also probably break *server side apply* in the future, because we would possibly shadow some state from the system

**Comment by tomwilkie** [comment]
> It feels to me as if there might be side-effects of an apply we cannot detect in diff, so we would miss those.

That kinda the point though?  We diff to show users what will change - if there are side-effects / something else changes, that is unexpected and surprising to the user.

We'd probably want this to be flag controlled and overridable for sure.

**Comment by sh0rez** [comment]
One thing I noticed, we cannot do this with subset-diff, because it does not reliably detect differences (e.g. it misses deleted fields).

Furthermore this would require another round of parsing (currently `kubectl diff` and subset just return raw `yaml`), to figure out what has changed. But the `diff` output might not include enough information to identify an object, because it redacts equal parts (which is the desired behaviour)
