### ISSUE TITLE
nonsensical phrase in docs about overriding

### ISSUE THREAD

**Issue by phormio** [grafana/tanka#461]
I can't make any sense of this phrase:

> for example by copying the one you actually next to your override

It appears here:

https://github.com/grafana/tanka/blob/d5c878e1754497607a3d76fba0c4ce823bcd128e/docs/docs/libraries/overriding.md#shadowing

**Comment by sh0rez** [comment]
Hi, good spot, that sentence should say:

```
for example by copying the one you actually need next to your override
```

The rationale behind lays in the file-choosing rules of the Jsonnet importer. Say you import `abc/main.libsonnet`, which in turn imports `abc/some.libsonnet`. Say 
you want to override `abc/some.libsonnet`. Those files are in `vendor/abc`.

Naturally, you would create `lib/abc/some.libsonnet`, because `lib` is ranked higher than `vendor`, so your override should work, right? No. 

When reading `import "some.libsonnet"` inside `"main.libsonnet"`, the Jsonnet importer first checks, if there is a file literally called `some.libsonnet` _right next_ to `main.libsonnet`, which is the case, so your `lib/abc/some.libsonnet` is never considered at all.

To fix that, you need to copy `main.libsonnet` to `lib/abc` as well, so the Jsonnet importer looks next to _your_ `main.libsonnet` instead.

Does that help you?

**Comment by sh0rez** [comment]
That docs section could definitely use an update. Are you interested in contributing that?

**Comment by phormio** [comment]
> Does that help you?

Yes.  But I suggest that you put that explanation in the docs, because they would still be unclear even after insertion of the missing word.

> That docs section could definitely use an update. Are you interested in contributing that?

I'm afraid not.

**Comment by phormio** [comment]
Please feel free to close this GitHub issue, by the way.
