### ISSUE TITLE
Transaction/Audit Log with Rollback Support

### ISSUE THREAD

**Issue by slim-bean** [grafana/tanka#48]
One of my biggest gripes with ksonnet is difficulty understanding what's been previously applied to an environment and by whom, and this directly relates to the other reason I would like a feature like this: rollback.

It would be nice if there were a centralized transaction log (or audit log?) which could be used to both see who's been making changes to ask them questions as well as make it easy to rollback a change gone wrong.

I figured I would start an issue to discuss the pros/cons and difficulties of such a feature.

**Comment by sh0rez** [comment]
Tanka is a utility for configuration as code (which is another form of infrastructure as code). These days, code usually lives in `git` repositories, which already has some kind of a transactional log of changes (good old `git log`).

Furthermore, the current trend seems to go towards [GitOps](https://www.weave.works/technologies/gitops/), which builds on that idea. In a world where Git can be considered the single source of truth, e.g. by using CD such as https://github.com/fluxcd/flux, changes could only ever be made by Pull Request, which IMHO is a perfect log, because it has rich discussions including justifications why a change is required and allows easy rollback using `git revert`.

I know that such a flow complicates operations and immediate response to issues, but this could be tackled using tools such as an *auto-approve-bot*, which automatically approves changes made by on-calls (effectively granting them the same privilege as using `kubectl` directly).

As another option Kubernetes has a built-in audit-log capabilities, which record any changes made to the system by everyone.

If we build something like what you outlined, I would like to keep it as minimal as possible (ie not build a service for keeping the log but rather build on what we already have).
