### ISSUE TITLE
tk init should also download the k8s libsonnet

### ISSUE THREAD

**Issue by gouthamve** [grafana/tanka#52]
Tanka is kubernetes focused but it's surprising that we need to download the k8s.libsonnet anyways using bundler. I would expect that `tk init` already contains the jsonnet required.

**Comment by sh0rez** [comment]
This is somewhat opinionated about what libraries somebody should use. 

So far Tanka is a rather open and general system which avoids assumptions and does not really impose anything (aside of using jsonnet).

Furthermore, there are multiple versions of this library (for different Kubernetes versions), while at `tk init` time, we do not know what cluster is going to be used. 

I would rather maintain both separately and suggest the use with each-other, but not force people to. Happy to discuss.
/cc @tomwilkie @malcolmholmes 


@gouthamve what about printing the `jb install` commands for those once `tk init` is done?

**Comment by daixiang0** [comment]
Add sub option like `tk init --k8s` to support this?

**Comment by sh0rez** [comment]
@daixiang0 this is tricky because won't be able to choose the correct version ... IE different versions of Kubernetes require different versions of the ksonnet libraries ... which are btw deprecated alongside with ksonnet.

So to really solve this, we need to first take over maintenance of these libraries (and the code gen) and then find a way to include the correct one, if desired (I still feel I wanna leave the choice to the user to do this using `jb`).

**Comment by daixiang0** [comment]
Yep, seems now hard to host all of them, right? Also, the relations about ks libs and ks version is not clear for users.

**Comment by sh0rez** [comment]
The term ksonnet is very ambiguous at the moment, because people use it to refer to different things at the moment:

1. The `ksonnet` CLI: The actual application, which Tanka replaces
2. Jsonnet: Some people use the term Ksonnet for Jsonnet itself, which is not correct, but because of the difference of only one character it easily happens
3. Ksonnet-Lib: A Jsonnet library generated from the `swagger.json` of a respective Kubernetes version

Because of this I wondered whether it would be better to move away from the term Ksonnet altogether and give the individual components of the projects separate names, for example:

- `kslib`, `libk8s`, `k.libsonnet` for the generated library
- Tanka for the CLI (we already have this)
- Make clear that the config language is called Jsonnet

**Comment by malcolmholmes** [comment]
@sh0rez this makes sense. Tanka is a CLI, not a language. The language is Jsonnet, which has some useful libraries, one of which is `k.libsonnet`.

**Comment by daixiang0** [comment]
@sh0rez i agree with that, make all of them clear is so cool!
