### ISSUE TITLE
Support for defining same object in multiple namespaces in export command

### ISSUE THREAD

**Issue by wojciechka** [grafana/tanka#528]
Some of the jsonnet files that I am trying to use tanka for are defining same objects in multiple namespaces - such as reusing same `Roles` across namespaces.

Tanka's default format for files does not include `.metadata.namespace`, so this is triggering the following error.

```
Error: File 'rendered/rbac.authorization.k8s.io-v1.Role-storage.yaml' already exists. Aborting
```

I can easily just use a custom value for `--format` - such as:

```
--format '{{.apiVersion}}.{{.kind}}-{{if .metadata.namespace}}{{.metadata.namespace}}-{{end}}{{.metadata.name}}'
```

Just wanted to report it and ask if `tk` should somehow handle it better on its own?

I think there is nothing that `tk` binary should be doing since anyone using Tanka can just provide custom formatting, but wanted to open the issue to make sure this is the best path forward.

**Comment by Duologic** [comment]
In the last iteration over the export code, we opted to not change the default format as we were already breaking other things.

Obviously we can't come up with a format that suits everybody's needs but maybe we can use this issue as an opportunity to list a number of format options that might be work. If we can come to a consensus, we could change the current default to that.

**Comment by nagyv** [comment]
I've run into a similar issue when I wanted to test-drive tanka. My idea was to start from the [`example.jsonnet` of kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) as the two projects seem to be related, and I thought that it should be simple to integrate.

It turned out that I was terribly wrong:

```
Error: File '../kubernetes/kube-prometheus/manifests/rbac.authorization.k8s.io-v1.Role-prometheus-k8s.yaml' already exists. Aborting
```

`kube-prometheus`'s build scripts creates files following their key in the jsonnet. As every key is unique by definition, this results in unique file names, but I could not find any way to pass the field name to `--format`.

**Comment by Duologic** [comment]
Would this do the trick? 
```
--format '{{.metadata.namespace}}/{{.kind}}-{{.metadata.name}}'
```
