### ISSUE TITLE
tk.env.metadata.name prefixes name with environments.

### ISSUE THREAD

**Issue by JacobSMoller** [grafana/tanka#548]
Hi, is it expected behaviour that if i have a spec.json like 

```{
  "apiVersion": "tanka.dev/v1alpha1",
  "kind": "Environment",
  "metadata": {
    "name": "test"
  },
  "spec": {
    "apiServer": some_ip,
    "resourceDefaults": {},
    "expectVersions": {}
  }
}
```
And then som libsonnet like:
```{
  local tk = import 'tk',
  local foo = tk.env.metadata.name
  }
```
Then foo comes out as `environments/test` 

And if its expected whats the reasoning behind it ? I think it seems wrong that tk.env automatically prefixes that name with anything.

**Comment by sh0rez** [comment]
Hey, this is indeed expected behavior. 

To quote the [relevant docs](https://tanka.dev/config):
>```js
>  "metadata": {
>    // Name of the Environment. Automatically set to the relative
>    // path from the project root
>    "name": "<string>",
>```

In other words, your environment is not prefix with `environments/`, but instead because it is at `<projectRoot>/environments/test` it automatically receives `environments/test` as it's name.  
An environment at `<projectRoot>/test` would receive `test`, and one at `<projectRoot>/somewhere/else` would receive `somewhere/else`.

The value you set in `spec.json` is ignored and overwritten to the generated one by any `tk env set` command

**Comment by JacobSMoller** [comment]
Cool thanks @sh0rez
