### ISSUE TITLE
Feature request: Create namespace from spec.json

### ISSUE THREAD

**Issue by a-nldisr** [grafana/tanka#689]
Making my first steps through Tanka, perhaps Im having a wrong understanding of things. Please forgive me if that's the case. 

My files: 
spec.json
```
{
  "apiVersion": "tanka.dev/v1alpha1",
  "kind": "Environment",
  "metadata": {
    "name": "environments/example"
  },
  "spec": {
    "apiServer": "https://example.com",
    "resourceDefaults": {},
    "expectVersions": {},
    "injectLabels": true,
    "namespace": "example"
  }
}
```

main.jssonnet
```
(import 'github.com/grafana/jsonnet-libs/ksonnet-util/kausal.libsonnet') +

{
  local configMap = $.core.v1.configMap,

  fooData:: {
    "foo-data": std.manifestYamlDoc({
      object: {
          "foo": "bar"
      }
    }),
  },

  configMapNginx: configMap.new("foo-data") +
    configMap.withData($.fooData) +
    configMap.metadata.withName("foo")
}
```

Output from Tanka CLI:
```
Error from server (NotFound): namespaces "example" not found
Error diffing: exit status 2
Applying to namespace 'example' of cluster... 
Please type 'yes' to confirm:
```

Tanka version: 
1.23

My questions:
Should the CLI output `Applying to namespace` not be `Applying to environment`?
Why does Tanka allow me to apply while there is an exit status 2?

Even more friendly to me as a user:
Would it be an idea to create a namespace instead of saying it is not found?

**Comment by Duologic** [comment]
You can add a core.v1.Namespace object to your Tanka environment if you'd like to manage your namespace that way, I believe Tanka does the ordering and ensure the namespaces gets applied first on `tk apply`.

Internally we have centralised the management of namespaces in another Tanka environment: https://grafana.com/blog/2021/07/12/best-practices-for-consistent-configuration-management-at-scale-with-tanka/#a-space-for-namespaces

> Would it be an idea to create a namespace instead of saying it is not found?

The respones for the non-existing namespace comes from `kubectl` directly, automatically creating a namespace has been a discussion in the kubernetes land for a while. AFAIK there is not concensus whether that is a good or bad idea. Personally I prefer to be explicit and manage namespaces deliberately rather than adding some magic to the client command. The current situation gives immediate feedback, for example I could have made a typo but would not notice that if Tanka/kubectl guessed that I want the namespace to be created.

> Should the CLI output `Applying to namespace` not be `Applying to environment`?

I agree it is a bit odd to say `namespace` here as it could also contain cluster-wide objects, but in general I don't think it cause much confusion.

> Why does Tanka allow me to apply while there is an exit status 2?

I don't know the precise answer, a quick scan through the code returns this explanation for the diff command:

https://github.com/grafana/tanka/blob/60775d3573df333d1076a68f165d8c9ff4acd8b3/pkg/kubernetes/client/diff.go#L64-L75

**Comment by a-nldisr** [comment]
> The respones for the non-existing namespace comes from `kubectl` directly, automatically creating a namespace has been a discussion in the kubernetes land for a while. AFAIK there is not concensus whether that is a good or bad idea. Personally I prefer to be explicit and manage namespaces deliberately rather than adding some magic to the client command. The current situation gives immediate feedback, for example I could have made a typo but would not notice that if Tanka/kubectl guessed that I want the namespace to be created.

My reasoning behind creating the namespace is that in the spec.json you already define a namespace in the spec.json, you could catch the kubectl error and create the namespace. Is the goal of Tanka to give a 1:1 experience compared to kubectl and add no additional features? If so then lets close this feature request. :) 

> I agree it is a bit odd to say namespace here as it could also contain cluster-wide objects, but in general I don't think it cause much confusion.

Let me give an example of my confusion as a new user then, in the spec.json defined the `example` namespace as the default namespace. When I apply the following main.jsonnet:

```
(import 'github.com/grafana/jsonnet-libs/ksonnet-util/kausal.libsonnet') +

{
  local configMap = $.core.v1.configMap,
  local namespace = $.core.v1.namespace,

  fooData:: {
    "foo-data": std.manifestYamlDoc({
      object: {
          "foo": "bar"
      }
    }),
  },

  addNamespace: namespace.new("example") +
    namespace.new("something"),

  configMapNginx: configMap.new("foo-data") +
    configMap.withData($.fooData) +
    configMap.metadata.withName("foo") +
    configMap.metadata.withNamespace("something")
}
```

output:
```
@@ -0,0 +1,11 @@
+apiVersion: v1
+data:
+  foo-data: |-
+    "object":
+      "foo": "bar"
+kind: ConfigMap
+metadata:
+  labels:
+    tanka.dev/environment: xyz
+  name: foo
+  namespace: something

Applying to namespace 'example' of cluster...
```
