### ISSUE TITLE
Tanka should take care of vendoring

### ISSUE THREAD

**Issue by cyriltovena** [grafana/tanka#75]
We currently have to install Jb to vendor jsonnet libraries.

It would be nice if Tanka has a command to deal with this without installing jb.

tk bundle vendor or something similar

**Comment by tankakatan** [comment]
Totally agree @cyriltovena. In my opinion Tanka should have a sort of dependency manager, like probably `npm`, `pip` or others. Otherwise I have to push my project's `vendor` folder (which is 4+ Mb large right after `tk init`) into my repository in order to support my CI process. It would be great to call something like `tk install` that would install all the dependencies from a file such as `requirements.txt` instead.

In my project I am currently implementing such functionality by wrapping tanka and jb in a docker image and running it as a standalone cli tool. But this obviously is a very weird solution. The image should also have `kubectl` and `docker` installed and a cluster configuration provided to it. I only managed to reduce the image size to 300mb so far. And the dependency managing part is still in progress.

**Comment by ghostsquad** [comment]
I don't see value in calling `tk install` over `jb install`. Also that jsonnet bundler is becoming the defacto standard for vendoring.

**Comment by sh0rez** [comment]
If we ever did it, it would only be `jb` exposed as `tk pkg`. Given there are efforts to find an upstream Jsonnet solution (which jb will maybe be part of), I don't think we should take action here yet, but follow whatever will be agreed on

**Comment by sh0rez** [comment]
Jsonnet Bundler fully covers the functionality and all serious development happens there, supported by Tanka. 
We couldn't do anything better, so we don't need to take action

**Comment by malcolmholmes** [comment]
The benefit of packaging within Tanka (i.e. vendoring in jb) is one less binary to install. This means one less concept for people to get when they first start exploring Tanka. This is very worthwhile. Having said that, if Jsonnet may be going to solve the problem, then waiting seems reasonable.

**Comment by ghostsquad** [comment]
I agree with @sh0rez I think that a tool should have a single responsibility, and to do that one thing well. Tanka should not introduce features that deviate from established norms regarding jsonnet management.
