### ISSUE TITLE
wrong env path

### ISSUE THREAD

**Issue by daixiang0** [grafana/tanka#79]
```
[root@test config]# tk env add loki --namespace loki
[root@test config]# ls environments/
default
[root@test config]# tk env list
NAME       NAMESPACE    SERVER    
default    default                
loki       loki   
[root@test config]# ls
environments  jsonnetfile.json  lib  loki  vendor
[root@test config]# ls loki/
main.jsonnet  spec.json
```
The new env dir should under `environments`.

**Comment by sh0rez** [comment]
Hi, this is actually working as intended, because Tanka is not opinionated about where an environment should live. Instead, every directory with a `main.jsonnet` is a valid one, regardless of where it is placed. The `environments/` folder is only a recommendation and does not need to be used.

Furthermore, `tk` always uses full folder paths to allow them being tab-completed

**Comment by daixiang0** [comment]
If it marked in doc or command help, it would be good!
@sh0rez
