### ISSUE TITLE
Color of diff changes when scrolling up and down

### ISSUE THREAD

**Issue by codesome** [grafana/tanka#82]
Example: https://www.youtube.com/watch?v=1UKlgCK2EeM

**Comment by cstyan** [comment]
I've had the same thing happen:

`tk version v0.3.0-11-g832fedb`
`Linux 5.2.14-arch2-1-ARCH x86_64 GNU/Linux`
`alacritty 0.3.3`

**Comment by codesome** [comment]
My versions:
* tk built from master at 06e745e4d0942400d4ce5cb0375049896d30df5f
* `Linux 5.0.0-29-generic #31~18.04.1-Ubuntu x86_64 GNU/Linux`

**Comment by sh0rez** [comment]
Alright, I can reproduce this (kind of). It behaves slightly differently but similar.

Looks like this happens only in combination with `less`, I'll look into it

**Comment by cstyan** [comment]
bump, go away stale bot

**Comment by codesome** [comment]
:eyes:

**Comment by sh0rez** [comment]
Tbh, I have no idea how to fix this. 

This issue only happens in combination with less, but I have no idea if we can tell less to not do this / if it is even possible to retain color output when scrolling up and down.

After all, colors in terminals are prefixed with these ANSI codes ... scrolling backwards means they would need to be prepended in the opposite order .. not easy, less would need to take care of this. Scrolling without a pager works fine, because it scrolls the output buffer of the terminal emulator up and down, instead of rewriting the entire screen

**Comment by cstyan** [comment]
Can we have the option of just dumping the output to stdout instead of less? I'd prefer to scroll via my own terminal or pipe to less explicitly.

**Comment by sh0rez** [comment]
Tanka tries to use your systems pager for this .. if you don't want one at all, would setting `PAGER=cat` work?

**Comment by cstyan** [comment]
Yes, that works via a shell function or alias. Is there any documentation anywhere of what env vars (:fire: ) tanka is making use of?

**Comment by sh0rez** [comment]
Afaict that’s the only one .. and no it’s not documented, but I will add it once I rewrite the docs

**Comment by cstyan** [comment]
For what it's worth I don't have this issue with `git diff` pagination
