### ISSUE TITLE
Move application logic out of main package

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/tanka#83]
As I understand it, writing a Golang utility that includes Tanka isn't possible (in an elegant way) because it doesn't expose an API.

It would be very useful if the commands were separated out into separate packages available by import into other go code.

**Comment by sh0rez** [comment]
Hi, I can definitely do this!

Could you elaborate a bit on the use-case, so I can better decide how to design it?

**Comment by malcolmholmes** [comment]
We have previously discussed the usecase. `tk tool imports` gives valuable output that I was initially consuming from Bash, then switched to NodeJS. Now it looks like we will use Golang. In which case, I will need to effectively invoke `tk tool imports` from Golang code instead of command line.

I've started hacking at it, will throw out a PR hopefully tomorrow, but I'm happy for you to do it too, as I'm not sure I'll have time to handle very command there is.

**Comment by sh0rez** [comment]
Ahh, okay!

So yes, I will definitely need to refactor `cli/tk` a bit, moving every logic out of there that is not directly related to the command line (ie `init` or `diff` is partly implemented in `package main`).

However, for your use-case you will probably not even need this, because you can just use `github.com/grafana/tanka/pkg/jsonnet.TransitiveImports("path_to_main.jsonnet")` to get a slice of all imports for a given `.jsonnet` file.

**Comment by malcolmholmes** [comment]
Ahh, that's useful. I'll also want `tk diff` too, but not right away.
